# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [5]:
import numpy as np

2. Create a null vector of size 10 

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [4]:
arr = np.arange(10, 49)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

4. Find the shape of previous array in question 3

In [5]:
# np.shape(arr)
arr.shape

(39,)

5. Print the type of the previous array in question 3

In [9]:
type(arr)

numpy.ndarray

6. Print the numpy version and the configuration


In [12]:
print(np.__version__)

1.18.1


In [13]:
print(np.show_config())

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/postgres/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/postgres/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/postgres/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mk

7. Print the dimension of the array in question 3

In [45]:
arr.ndim

1

8. Create a boolean array with all the True values

In [46]:
# 1
# bools = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
# bools > 0

# 2
np.ones(([3, 3]), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

9. Create a two dimensional array

In [9]:
arr2d = np.array([[0, 1, 2],[3, 4, 5]])
arr2d

array([[0, 1, 2],
       [3, 4, 5]])

10. Create a three dimensional array

In [11]:
arr3d = np.arange(27).reshape(3,3,3)
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [12]:
vect = np.arange( 11, 39)
# made a vector with values from 11 to 39
vect

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38])

In [13]:
# Now Reversed vector 'vect'
r_vect = vect[::-1]
r_vect

array([38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22,
       21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11])

12. Create a null vector of size 10 but the fifth value which is 1 

In [96]:
n_vect = np.zeros(10)
n_vect[4] = 1
n_vect

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [100]:
# i_matrix = np.identity(3)

i_matrix = np.eye(3)
i_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [15]:
arr_float = np.array([1, 2, 3, 4, 5], np.float64)
arr_float

array([1., 2., 3., 4., 5.])

15. arr1 = np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [122]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
multiply = (arr1 * arr2)
multiply

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [18]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

# np.where(arr1 == arr2, arr1, arr2

arr1 == arr2

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [20]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
odd_nums = arr[arr%2 == 1]
odd_nums

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [27]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [166]:
arr = np.arange(10)
arr[5:-1] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [28]:
arr = np.ones([5, 5])
arr[1:-1, 1:-1] = 0
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [177]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[1:-1, 1:-1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [30]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0] = 64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [71]:
arr2d = np.arange(10).reshape(2,5)
arr2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [87]:
# Sliced out the 1st value 1-D array
arr2d[1:, :]

array([[5, 6, 7, 8, 9]])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [225]:
arr2d = np.arange(10).reshape(2,5)
arr2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [94]:
# Sliced out the 1st value 1-D array
arr2d[:1, :]

array([[0, 1, 2, 3, 4]])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [227]:
arr2d = np.arange(10).reshape(2,5)
arr2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [155]:
# Sliced out the 3rd column
arr2d[ : , 2:-2]

array([[2],
       [7]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [157]:
arr = np.random.randn(10,10)
arr

array([[ 0.80045139,  0.43504666,  1.11638959,  0.58454565, -1.97497647,
         2.15157229, -1.56880138,  0.6921211 ,  0.01832828,  0.21491163],
       [ 0.3403157 ,  0.0674768 ,  0.68716775, -0.58332319, -0.60536425,
        -0.13950281, -0.54221762,  0.12758252, -0.82986074,  0.19529561],
       [-0.50195068, -1.58465508, -1.60583999, -1.60196577, -1.33166792,
         1.2356982 ,  0.63257117, -0.21317248,  0.57875409, -2.49968531],
       [ 0.49859129,  0.41454091,  0.04421922,  0.43671605,  0.88428759,
        -0.25629772, -0.8374052 , -0.02512922, -0.09281425,  0.24063363],
       [ 1.4660088 , -0.29031288, -1.00776583, -0.24356933, -0.62136244,
        -0.43824125, -0.84518991,  3.43418429, -1.37614425,  0.69269198],
       [ 0.98524598,  0.69569878, -0.18614752,  0.20309218,  1.04378724,
         0.0384875 ,  0.43934378, -0.85521561, -0.35037114,  0.92225849],
       [-0.60533175, -1.8375234 ,  0.66837703,  2.36775192, -0.24845151,
        -0.57428057,  0.51492574,  0.07084141

In [159]:
# Minimun value
arr.min()

-2.499685311254956

In [160]:
# Maximum value
arr.max()

3.4341842880618465

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [163]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c_items = np.intersect1d(a, b)
c_items

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [168]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b )

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [170]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

# Also We can use only this command at this point
# data[~(names == 'Will')]

In [424]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [425]:
data

array([[-0.56909172,  0.42727445,  0.95765238,  0.73086843],
       [ 0.4032573 ,  0.22161551,  0.59987672,  0.77495925],
       [-1.42285605, -0.32603182,  0.67517518,  1.61820759],
       [ 0.07571015, -0.10600549,  0.50266776, -0.19973716],
       [ 1.38144875, -1.46992333, -2.38556478,  0.82489955],
       [-0.70284308,  0.39525325,  0.23294962,  0.98741282],
       [ 0.99672369, -0.34616129, -0.93998704, -0.32440899]])

In [426]:
names != 'Will'

array([ True,  True, False,  True, False,  True,  True])

In [428]:
data[~(names == 'Will')]

array([[-0.56909172,  0.42727445,  0.95765238,  0.73086843],
       [ 0.4032573 ,  0.22161551,  0.59987672,  0.77495925],
       [ 0.07571015, -0.10600549,  0.50266776, -0.19973716],
       [-0.70284308,  0.39525325,  0.23294962,  0.98741282],
       [ 0.99672369, -0.34616129, -0.93998704, -0.32440899]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [171]:
mask = ((names != 'Will') & (names != 'Joe'))
mask

array([ True, False, False,  True, False, False, False])

In [172]:
# Values from tha data
data[~(names == mask)]

C:\Users\postgres\anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  


array([ 1.34150792, -0.22387636,  1.46390054,  1.26413236])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [496]:
arr = np.random.randn(15).reshape(5, 3)
arr.astype(np.float64)

array([[-0.37759625,  0.88983856,  1.29984874],
       [ 1.5075814 , -0.55463409, -1.94329113],
       [ 2.65013662,  1.3092735 ,  0.45240824],
       [-0.57882376, -0.59178009, -0.70021135],
       [ 1.16408948, -0.24428499,  0.69419191]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [176]:
arr = np.random.randn(16).reshape(2,2,4)
arr

array([[[-0.72509616, -0.67382183,  0.30462739, -0.07937525],
        [-0.23120264,  0.4979667 , -0.8081945 , -0.31812494]],

       [[-0.86684324,  1.0031121 , -0.7757634 , -2.95124001],
        [-1.5977308 , -0.41728649,  0.58353172, -0.39357487]]])

In [177]:
arr = arr.astype(np.float64)
arr

array([[[-0.72509616, -0.67382183,  0.30462739, -0.07937525],
        [-0.23120264,  0.4979667 , -0.8081945 , -0.31812494]],

       [[-0.86684324,  1.0031121 , -0.7757634 , -2.95124001],
        [-1.5977308 , -0.41728649,  0.58353172, -0.39357487]]])

33. Swap axes of the array you created in Question 32

In [175]:
arr.swapaxes(1, 2)

array([[[ 1.88069769, -1.87259413],
        [-0.0731107 ,  1.39755416],
        [ 0.48486871, -1.19005751],
        [-0.4017331 ,  0.66478994]],

       [[ 0.2155351 ,  1.74813397],
        [ 0.18699151,  0.92499877],
        [-0.13004161, -0.32646741],
        [ 0.48079394,  0.72740118]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [179]:
arr = np.arange(10).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [180]:
# Square root of every element
srt= np.sqrt(arr)
srt

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ]])

In [181]:
# Condition 'Where 0.5 = 0' apply 
np.where(srt < 0.5, 0, srt)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ]])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [193]:
arr1 = np.random.randn(12).reshape(2, 6)
arr1

array([[ 1.54487443,  0.88532962,  0.91320498,  0.59473768, -0.51756277,
        -1.47237868],
       [ 0.38189927,  0.02776869,  0.49234782,  0.77940707,  0.38476978,
         0.51761881]])

In [194]:
arr2 = np.random.randn(12).reshape(2, 6)
arr2

array([[-0.66379518, -0.4063688 , -2.27095564,  1.32196084, -0.08336408,
        -1.35539977],
       [-1.94458675, -0.09496017, -0.2830488 ,  0.92259553, -0.65162689,
         1.75690604]])

In [202]:
np.maximum( arr1, arr2)

array([[ 1.54487443,  0.88532962,  0.91320498,  1.32196084, -0.08336408,
        -1.35539977],
       [ 0.38189927,  0.02776869,  0.49234782,  0.92259553,  0.38476978,
         1.75690604]])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [272]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [275]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.sort(names)

array(['Bob', 'Bob', 'Joe', 'Joe', 'Joe', 'Will', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [289]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
np.setdiff1d(a, b)

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [254]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
# col=np.vstack(newColumn)
# col
sampleArray

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [257]:
newColumn = sampleArray[:, 1:-1] = newColumn
sampleArray

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [258]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [260]:
arr = np.random.randn(4, 5)
arr

array([[ 0.82820103, -0.75616745, -0.1606234 , -1.8249062 ,  0.71579576],
       [ 0.4385041 , -0.23554006, -1.59148427, -0.37542205,  0.61900639],
       [ 1.53514632,  0.25380693, -0.59439976, -0.29929832, -1.2069659 ],
       [-0.75248688, -1.14380225, -0.64148374,  1.63661773,  0.73130194]])

In [261]:
cumsum = np.cumsum(arr)
cumsum

array([ 0.82820103,  0.07203358, -0.08858983, -1.91349603, -1.19770027,
       -0.75919617, -0.99473624, -2.58622051, -2.96164256, -2.34263617,
       -0.80748986, -0.55368292, -1.14808269, -1.447381  , -2.65434691,
       -3.40683378, -4.55063603, -5.19211977, -3.55550204, -2.8242001 ])

In [263]:

# Numpy_Assignment_2


In [331]:
# Question:1
# Convert a 1D array to a 2D array with 2 rows?
# Desired output::
# array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])

arr = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [272]:
# Question:2
# How to stack two arrays vertically?
# Desired Output::
arr = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [273]:
# Question:3
# How to stack two arrays horizontally?
# Desired Output::

arr = np.array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1], [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
arr

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [275]:
# Question:4
# How to convert an array of arrays into a flat 1d array?
# Desired Output::

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [277]:
# Question:5
# How to Convert higher dimension into one dimension?
# Desired Output::
arr = np.array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [279]:
# Question:6
# Convert one dimension to higher dimension?
# Desired Output::

arr = np.array([[ 0, 1, 2], [ 3, 4, 5], [ 6, 7, 8], [ 9, 10, 11], [12, 13, 14]])
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [296]:
# Question:7
# Create 5x5 an array and find the square of an array?
arr = np.arange(25).reshape(5,5)
np.square(arr)

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

In [298]:
# Question:8
# Create 5x6 an array and find the mean?
arr = np.arange(30).reshape(5,6)
np.mean(arr)

14.5

In [299]:
# Question:9
# Find the standard deviation of the previous array in Q8?
arr = np.arange(30).reshape(5,6)
np.std(arr)

8.65544144839919

In [302]:
# Question:10
# Find the median of the previous array in Q8?
arr = np.arange(30).reshape(5,6)
np.median(arr)

14.5

In [ ]:
# Question:11
# Find the transpose of the previous array in Q8?

In [303]:
arr = np.arange(30).reshape(5,6)
arr.T

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

In [316]:
# Question:12
# Create a 4x4 an array and find the sum of diagonal elements?

arr = np.arange(16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [317]:
# sum of diagonal elements
np.trace(arr)

30

In [318]:
# Question:13
# Find the determinant of the previous array in Q12?
arr = np.arange(16).reshape(4,4)
np.linalg.det(arr)

0.0

In [321]:
# Question:14
# Find the 5th and 95th percentile of an array?
arr = np.arange(16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [322]:
# 5th and 95th percentile
np.percentile(arr, 5)

0.75

In [323]:
# 95th and 95th percentile
np.percentile(arr, 95)

14.25

In [327]:
# Question:15
# How to find if a given array has any null values?
arr = np.isnan(arr)
arr

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])